version: '3'
services:
  app:
    build: .
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./storage:/app/storage
    restart: ${RESTART_POLICY:-always}
    environment:
      - RUN_RAILS=true
      - RUN_SIDEKIQ=false
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:decidim@db/decidim}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-132a6ee88fe7cbc9bfd8f6dfeda5casdf03d0278e16dd40ec199109acde7fdda524d495a013d20e2b962dbafb61234136278ea6d6ac2c134776bd445da9671e}
      - DECIDIM_FORCE_SSL=${DECIDIM_FORCE_SSL:-false}
      - QUEUE_ADAPTER=${QUEUE_ADAPTER:-sidekiq}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-2}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - MAPS_PROVIDER=${MAPS_PROVIDER:-here}
      - DECIDIM_ENABLE_HTML_HEADER_SNIPPETS=${DECIDIM_ENABLE_HTML_HEADER_SNIPPETS:-true}
      - DECIDIM_ADMIN_PASSWORD_EXPIRATION_DAYS=${DECIDIM_ADMIN_PASSWORD_EXPIRATION_DAYS:-0}
      - CHANGE_ACTIVE_STEP=${CHANGE_ACTIVE_STEP:-enabled}
      - SEND_REMINDERS=${SEND_REMINDERS:-enabled}
      - WEEKLY_NOTIFICATIONS_DIGEST=${WEEKLY_NOTIFICATIONS_DIGEST:-enabled}
      - DAILY_NOTIFICATIONS_DIGEST=${DAILY_NOTIFICATIONS_DIGEST:-enabled}
      - SMTP_STARTTLS_AUTO=${SMTP_STARTTLS_AUTO:-true}
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_ADDRESS
      - SMTP_DOMAIN=${SMTP_DOMAIN:-getxo.eus}
      - SMTP_PORT=${SMTP_PORT:-25}
      - DECIDIM_MAILER_SENDER
      - MAPS_API_KEY
      - MAPS_PROVIDER=${MAPS_PROVIDER:-here}
      - RACK_ATTACK_SECRET
      - CENSUS_URL
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
  sidekiq:
    build: .
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./storage:/app/storage
    restart: ${RESTART_POLICY:-always}
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:decidim@db/decidim}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-132a6ee88fe7cbc9bfd8f6dfeda5casdf03d0278e16dd40ec199109acde7fdda524d495a013d20e2b962dbafb61234136278ea6d6ac2c134776bd445da9671e}
      - DECIDIM_FORCE_SSL=${DECIDIM_FORCE_SSL:-false}
      - QUEUE_ADAPTER=${QUEUE_ADAPTER:-sidekiq}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - RUN_RAILS=false
      - RUN_SIDEKIQ=true
      - SIDEKIQ_CONCURRENCY=${SIDEKIQ_CONCURRENCY:-5}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - MAPS_PROVIDER=${MAPS_PROVIDER:-here}
      - DECIDIM_ENABLE_HTML_HEADER_SNIPPETS=${DECIDIM_ENABLE_HTML_HEADER_SNIPPETS:-true}
      - DECIDIM_ADMIN_PASSWORD_EXPIRATION_DAYS=${DECIDIM_ADMIN_PASSWORD_EXPIRATION_DAYS:-0}
      - CHANGE_ACTIVE_STEP=${CHANGE_ACTIVE_STEP:-enabled}
      - SEND_REMINDERS=${SEND_REMINDERS:-enabled}
      - WEEKLY_NOTIFICATIONS_DIGEST=${WEEKLY_NOTIFICATIONS_DIGEST:-enabled}
      - DAILY_NOTIFICATIONS_DIGEST=${DAILY_NOTIFICATIONS_DIGEST:-enabled}
      - SMTP_STARTTLS_AUTO=${SMTP_STARTTLS_AUTO:-true}
      - DECIDIM_MAILER_SENDER
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_ADDRESS
      - SMTP_DOMAIN=${SMTP_DOMAIN:-getxo.eus}
      - SMTP_PORT=${SMTP_PORT:-25}
      - MAPS_API_KEY
      - MAPS_PROVIDER=${MAPS_PROVIDER:-here}
      - RACK_ATTACK_SECRET
      - CENSUS_URL
    depends_on:
      - db
      - redis
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-decidim}
      - POSTGRES_DB=${POSTGRES_DB:-decidim}
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data
volumes:
  pg_data:
  redis_data: