FROM nginx

RUN apt-get update -qq && apt-get -y install apache2-utils

ENV HOST="zeugaz.getxo.eus"
WORKDIR /app

RUN mkdir log

COPY public /app/public/
COPY nginx.conf /tmp/docker.nginx

RUN envsubst '$HOST' < /tmp/docker.nginx > /etc/nginx/conf.d/default.conf

EXPOSE 80
EXPOSE 443

CMD [ "nginx", "-g", "daemon off;" ]